server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

#brasilprev:
#  swagger:
#    baseUrl: ${SWAGGER_BASE_URL:localhost:${server.port}}
#    apiInfo: REST API for Brasilprev Service Microservice
#      apiTitle: Brasilprev Service

security:
  jwt:
    expiry: 3000
    key: abcde