server:
  port: ${PORT:8080}

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

brasilprev:
    swagger:
    baseUrl: ${SWAGGER_BASE_URL:localhost:${server.port}}
    apiInfo: REST API for Brasilprev Service Microservice
    apiTitle: BrasilPrev Services

security:
  jwt:
    expiry: 3000
    key: ${JWT_KEY:abcde}